--- #YAML:1.0
name:               PerlIO-locale
version:            0.08
abstract:           ~
author:
    - Leon Timmermans <leont@cpan.org>, Rafael Garcia-Suarez <rgs@consttype.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    PerlIO::encoding:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
